/**
 * ==========================================================================
 * COSMIC ENIGMAS - INTERACTIVE JAVASCRIPT CORNERSTONE
 * ==========================================================================
 */

// Global App State
const state = {
    activeEnigma: 0,
    starfield: {
        stars: [],
        nebulae: [],
        mouse: { x: 0, y: 0, targetX: 0, targetY: 0 }
    },
    audio: {
        context: null,
        ambientNode: null,
        gainNode: null,
        isPlaying: false,
        humNode: null // Used for decoder signal feedback
    },
    simulator: {
        canvas: null,
        ctx: null,
        animationId: null,
        time: 0,
        // Specific parameters updated by inputs
        params: {}
    },
    decoder: {
        canvas: null,
        ctx: null,
        animationId: null,
        target: { freq: 48, filter: 15, phase: 180, gain: 65 },
        current: { freq: 30, filter: 45, phase: 120, gain: 15 },
        isAligned: false,
        terminalTimeout: null
    },
    drawer: {
        isOpen: false,
        activeTab: 0
    }
};

// Data Store for cosmic phenomena
const ENIGMAS_DATA = [
    {
        title: "Supermassive Black Hole",
        coords: "RA 17h 45m 40s / Dec -29° 0' 28\"",
        description: "A supermassive singularity located at the galactic core. Spacetime curvature is infinite, and light is bent irrevocably into its event horizon.",
        logs: [
            "Initializing event horizon telemetry...",
            "Warping coefficient of adjacent starlight calculated at G=8.42x10^9.",
            "Accretion disk thermal reading: 1.2x10^7 Kelvin.",
            "Gravity well collapse is infinite in the core. Time dilation factor approaches infinity at r=r_s."
        ],
        controls: [
            { id: "bh-mass", label: "Horizon Radius (r_s)", min: 10, max: 80, value: 40, unit: "km x1000", type: "mass" },
            { id: "bh-spin", label: "Accretion Spin", min: 1, max: 20, value: 5, unit: "c %", type: "spin" },
            { id: "bh-lensing", label: "Lensing Warp", min: 1, max: 10, value: 6, unit: "x", type: "lensing" }
        ]
    },
    {
        title: "Dark Matter Cosmic Scaffold",
        coords: "RA 12h 21m 12s / Dec +14° 36' 18\"",
        description: "The invisible scaffolding of the universe. Dark matter clusters in filaments, attracting baryonic matter to form galaxies, while dark energy drives space apart.",
        logs: [
            "Mapping non-baryonic matter distribution...",
            "Gravitational lensing confirms filament densities exceeding critical mass.",
            "Cosmic web node connections computed at 4,821 adjacent cluster branches.",
            "Expansion velocity increases exponentially: H_0 adjusted dynamically."
        ],
        controls: [
            { id: "dm-density", label: "Dark Matter Density", min: 5, max: 50, value: 20, unit: "GeV/cm³", type: "density" },
            { id: "dm-expansion", label: "Expansion Velocity", min: 0, max: 15, value: 3, unit: "km/s/Mpc", type: "expansion" },
            { id: "dm-nodes", label: "Filament Nodes", min: 10, max: 100, value: 40, unit: "qty", type: "nodes" }
        ]
    },
    {
        title: "Fast Radio Burst (FRB)",
        coords: "RA 05h 31m 58s / Dec +33° 08' 04\"",
        description: "An ultra-powerful millisecond pulse of radio emission originating from deep intergalactic space, possibly generated by a hyper-magnetized magnetar.",
        logs: [
            "Receiving millisecond cosmic transient flux...",
            "Dispersion measure (DM) indicates travel distance of 4.2 billion light years.",
            "Magnetosphere magnetic strength: B = 10^15 Gauss.",
            "Coherent curvature radiation spike observed at S/N ratio 84.1."
        ],
        controls: [
            { id: "frb-freq", label: "Burst Frequency", min: 10, max: 100, value: 40, unit: "GHz", type: "freq" },
            { id: "frb-dispersion", label: "Dispersion Measure", min: 100, max: 1500, value: 700, unit: "pc/cm³", type: "dispersion" },
            { id: "frb-pulse", label: "Pulse Envelope", min: 2, max: 30, value: 8, unit: "ms", type: "pulse" }
        ]
    },
    {
        title: "Nomadic Rogue Planet",
        coords: "RA 08h 12m 44s / Dec -05° 40' 12\"",
        description: "A gigantic, starless gas world drifting alone through interstellar space, cooled to near absolute zero but possessing volcanic geothermal cracks under the ice.",
        logs: [
            "Engaging infrared thermal matrix scanner...",
            "Reflectance spectrum confirms heavy surface crystallizations of water and methane ice.",
            "Core heat convection remains active. Deep geothermal thermal vents detected.",
            "Magnetic field: weak dipole, protecting a thin atmosphere of noble gases."
        ],
        controls: [
            { id: "rp-scanner", label: "IR Scan Frequency", min: 5, max: 50, value: 15, unit: "Hz", type: "scanner" },
            { id: "rp-temp", label: "Geothermal Activity", min: 1, max: 10, value: 3, unit: "kW/m²", type: "temp" },
            { id: "rp-filter", label: "Atmosphere Filter", min: 0, max: 5, value: 2, unit: "opt", type: "filter" }
        ]
    },
    {
        title: "The Great Attractor Anomaly",
        coords: "RA 10h 32m 00s / Dec -48° 30' 00\"",
        description: "A colossal gravitational anomaly in the center of the Laniakea Supercluster, pulling our Milky Way and thousands of other galaxies towards its enigmatic mass.",
        logs: [
            "Tracking galactic coordinate velocity vector deviation...",
            "Local cluster drift vector: 620 km/s in direction of Centaurus.",
            "Attractor core mass estimation: 10^16 Solar Masses.",
            "Zone of avoidance obscurants (interstellar dust) blocking 92% of optical data."
        ],
        controls: [
            { id: "ga-pull", label: "Gravitational Pull", min: 10, max: 100, value: 50, unit: "G x10^12", type: "pull" },
            { id: "ga-count", label: "Galaxy Clusters", min: 5, max: 80, value: 30, unit: "clusters", type: "count" },
            { id: "ga-dust", label: "Obscurant Dust Density", min: 10, max: 90, value: 45, unit: "%", type: "dust" }
        ]
    }
];

// Fallback visualizers for cards in case images fail
function handleImageError(img, index) {
    const parent = img.parentElement;
    parent.innerHTML = ''; // Clear image
    const canvas = document.createElement('canvas');
    canvas.className = 'fallback-canvas';
    parent.appendChild(canvas);
    
    const ctx = canvas.getContext('2d');
    canvas.width = parent.clientWidth || 350;
    canvas.height = 220;
    
    // Draw beautiful fallback starry art
    ctx.fillStyle = '#060713';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Simple generative space art for fallbacks
    if (index === 0) { // Black hole
        const cx = canvas.width / 2;
        const cy = canvas.height / 2;
        const grad = ctx.createRadialGradient(cx, cy, 10, cx, cy, 70);
        grad.addColorStop(0, '#000000');
        grad.addColorStop(0.3, '#f59e0b');
        grad.addColorStop(0.6, '#ec4899');
        grad.addColorStop(1, 'transparent');
        ctx.fillStyle = grad;
        ctx.beginPath();
        ctx.arc(cx, cy, 70, 0, Math.PI * 2);
        ctx.fill();
        ctx.fillStyle = '#000';
        ctx.beginPath();
        ctx.arc(cx, cy, 25, 0, Math.PI * 2);
        ctx.fill();
    } else if (index === 1) { // Dark matter
        ctx.strokeStyle = 'rgba(139, 92, 246, 0.4)';
        ctx.lineWidth = 1;
        const points = [];
        for (let i = 0; i < 20; i++) {
            points.push({ x: Math.random() * canvas.width, y: Math.random() * canvas.height });
        }
        for (let i = 0; i < points.length; i++) {
            for (let j = i + 1; j < points.length; j++) {
                const dist = Math.hypot(points[i].x - points[j].x, points[i].y - points[j].y);
                if (dist < 100) {
                    ctx.beginPath();
                    ctx.moveTo(points[i].x, points[i].y);
                    ctx.lineTo(points[j].x, points[j].y);
                    ctx.stroke();
                }
            }
            ctx.fillStyle = '#06b6d4';
            ctx.beginPath();
            ctx.arc(points[i].x, points[i].y, 2, 0, Math.PI * 2);
            ctx.fill();
        }
    } else if (index === 2) { // FRB
        ctx.strokeStyle = '#ec4899';
        ctx.lineWidth = 2;
        ctx.beginPath();
        for (let x = 0; x < canvas.width; x++) {
            const y = canvas.height / 2 + Math.sin(x * 0.1) * 30 * Math.exp(-Math.pow((x - canvas.width/2)/40, 2));
            if (x === 0) ctx.moveTo(x, y);
            else ctx.lineTo(x, y);
        }
        ctx.stroke();
    } else if (index === 3) { // Rogue planet
        const cx = canvas.width / 2;
        const cy = canvas.height / 2;
        const grad = ctx.createRadialGradient(cx - 15, cy - 15, 5, cx, cy, 50);
        grad.addColorStop(0, '#1e293b');
        grad.addColorStop(0.8, '#0b0f19');
        grad.addColorStop(1, '#020617');
        ctx.fillStyle = grad;
        ctx.beginPath();
        ctx.arc(cx, cy, 50, 0, Math.PI * 2);
        ctx.fill();
        
        ctx.strokeStyle = 'rgba(168, 85, 247, 0.4)';
        ctx.beginPath();
        ctx.arc(cx, cy, 50, 0, Math.PI * 2);
        ctx.stroke();
    } else { // Great attractor
        const cx = canvas.width / 2;
        const cy = canvas.height / 2;
        ctx.strokeStyle = 'rgba(239, 68, 68, 0.2)';
        for (let r = 10; r < 90; r += 15) {
            ctx.beginPath();
            ctx.arc(cx, cy, r, 0, Math.PI * 2);
            ctx.stroke();
        }
        ctx.fillStyle = '#ef4444';
        ctx.beginPath();
        ctx.arc(cx, cy, 6, 0, Math.PI * 2);
        ctx.fill();
    }
}

/* ==========================================================================
   INITIALIZATION & BACKGROUND ENGINE
   ========================================================================== */

document.addEventListener('DOMContentLoaded', () => {
    initStarfield();
    initObservatory();
    initDecoder();
    initStudentDrawer();
    setupEventListeners();
    animateStarfield();
});

// Setup Starfield Particle System
function initStarfield() {
    const canvas = document.getElementById('starfield-canvas');
    const ctx = canvas.getContext('2d');
    
    function resizeCanvas() {
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
        generateStars(canvas.width, canvas.height);
    }
    
    window.addEventListener('resize', resizeCanvas);
    resizeCanvas();
    
    // Handle mouse movement to shift depth
    window.addEventListener('mousemove', (e) => {
        state.starfield.mouse.targetX = (e.clientX - window.innerWidth / 2) * 0.05;
        state.starfield.mouse.targetY = (e.clientY - window.innerHeight / 2) * 0.05;
    });
}

function generateStars(w, h) {
    state.starfield.stars = [];
    const count = Math.min(250, Math.floor((w * h) / 6000));
    
    for (let i = 0; i < count; i++) {
        state.starfield.stars.push({
            x: Math.random() * w,
            y: Math.random() * h,
            size: Math.random() * 1.5 + 0.5,
            twinkleSpeed: Math.random() * 0.03 + 0.005,
            twinklePhase: Math.random() * Math.PI,
            depth: Math.random() * 0.8 + 0.2, // Depth factor for parallax
            color: getRandomStellarColor()
        });
    }

    // Generate soft floating cosmic clouds
    state.starfield.nebulae = [];
    for (let i = 0; i < 3; i++) {
        state.starfield.nebulae.push({
            x: Math.random() * w,
            y: Math.random() * h,
            radius: Math.random() * 250 + 150,
            color: i === 0 ? 'rgba(180, 100, 255, 0.08)' : (i === 1 ? 'rgba(0, 242, 254, 0.06)' : 'rgba(219, 39, 119, 0.06)'),
            vx: (Math.random() - 0.5) * 0.15,
            vy: (Math.random() - 0.5) * 0.15
        });
    }
}

function getRandomStellarColor() {
    const colors = [
        '#ffffff', // White
        '#e0f2fe', // Soft Blue
        '#fae8ff', // Soft Pink
        '#bae6fd', // Cyan-Blue
        '#fef08a'  // Light Yellow
    ];
    return colors[Math.floor(Math.random() * colors.length)];
}

function animateStarfield() {
    const canvas = document.getElementById('starfield-canvas');
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    
    // Clear & redraw space background
    ctx.fillStyle = '#040509';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Smoothly interpolate mouse parallax shifts
    state.starfield.mouse.x += (state.starfield.mouse.targetX - state.starfield.mouse.x) * 0.05;
    state.starfield.mouse.y += (state.starfield.mouse.targetY - state.starfield.mouse.y) * 0.05;
    
    // 1. Draw Nebulae clouds first (deep space back)
    ctx.globalCompositeOperation = 'screen';
    state.starfield.nebulae.forEach(n => {
        // Drifting motion
        n.x += n.vx;
        n.y += n.vy;
        
        // Bounce bounds
        if (n.x < -n.radius) n.x = canvas.width + n.radius;
        if (n.x > canvas.width + n.radius) n.x = -n.radius;
        if (n.y < -n.radius) n.y = canvas.height + n.radius;
        if (n.y > canvas.height + n.radius) n.y = -n.radius;
        
        const shiftX = n.x + state.starfield.mouse.x * 0.1;
        const shiftY = n.y + state.starfield.mouse.y * 0.1;
        
        const grad = ctx.createRadialGradient(shiftX, shiftY, 0, shiftX, shiftY, n.radius);
        grad.addColorStop(0, n.color);
        grad.addColorStop(1, 'transparent');
        ctx.fillStyle = grad;
        ctx.beginPath();
        ctx.arc(shiftX, shiftY, n.radius, 0, Math.PI * 2);
        ctx.fill();
    });
    ctx.globalCompositeOperation = 'source-over';
    
    // 2. Draw stars with twinkling phase and depth parallax
    state.starfield.stars.forEach(s => {
        s.twinklePhase += s.twinkleSpeed;
        const alpha = 0.3 + Math.abs(Math.sin(s.twinklePhase)) * 0.7;
        
        // Apply parallax offset based on star depth and mouse position
        const posX = s.x + state.starfield.mouse.x * s.depth;
        const posY = s.y + state.starfield.mouse.y * s.depth;
        
        // Wrap stars around viewport bounds
        let finalX = posX % canvas.width;
        let finalY = posY % canvas.height;
        if (finalX < 0) finalX += canvas.width;
        if (finalY < 0) finalY += canvas.height;
        
        ctx.fillStyle = s.color;
        ctx.globalAlpha = alpha;
        ctx.beginPath();
        ctx.arc(finalX, finalY, s.size, 0, Math.PI * 2);
        ctx.fill();
    });
    ctx.globalAlpha = 1.0;
    
    requestAnimationFrame(animateStarfield);
}

/* ==========================================================================
   WEB AUDIO API SOUNDSCAPE
   ========================================================================== */

function setupAudio() {
    if (state.audio.context) return;
    
    const AudioContext = window.AudioContext || window.webkitAudioContext;
    state.audio.context = new AudioContext();
    
    // 1. Create a deep space ambient drone hum
    const osc1 = state.audio.context.createOscillator();
    const osc2 = state.audio.context.createOscillator();
    const lfo = state.audio.context.createOscillator();
    
    const lfoGain = state.audio.context.createGain();
    const filter = state.audio.context.createBiquadFilter();
    state.audio.gainNode = state.audio.context.createGain();
    
    // Set oscillator frequencies for dark bass chord (C1 & G1)
    osc1.type = 'sine';
    osc1.frequency.setValueAtTime(65.41, state.audio.context.currentTime); // C2
    osc2.type = 'triangle';
    osc2.frequency.setValueAtTime(98.00, state.audio.context.currentTime); // G2
    
    // LFO to slowly sweep filter frequency (creating a breathing wind/drone)
    lfo.frequency.setValueAtTime(0.08, state.audio.context.currentTime); // very slow
    lfoGain.gain.setValueAtTime(120, state.audio.context.currentTime);
    
    filter.type = 'lowpass';
    filter.Q.setValueAtTime(3.5, state.audio.context.currentTime);
    filter.frequency.setValueAtTime(220, state.audio.context.currentTime);
    
    // Connect nodes
    lfo.connect(lfoGain);
    lfoGain.connect(filter.frequency);
    
    osc1.connect(filter);
    osc2.connect(filter);
    
    // Dynamic soft volume
    state.audio.gainNode.gain.setValueAtTime(0.0, state.audio.context.currentTime); // Start silent
    filter.connect(state.audio.gainNode);
    state.audio.gainNode.connect(state.audio.context.destination);
    
    // Start oscillators
    osc1.start();
    osc2.start();
    lfo.start();
    
    state.audio.ambientNode = { osc1, osc2, lfo, filter };
}

function toggleSoundscape() {
    const btn = document.getElementById('audio-toggle');
    if (!btn) return;
    const label = btn.querySelector('span');
    const icon = btn.querySelector('i');
    
    setupAudio();
    
    if (state.audio.context.state === 'suspended') {
        state.audio.context.resume();
    }
    
    if (state.audio.isPlaying) {
        // Fade out
        state.audio.gainNode.gain.linearRampToValueAtTime(0.0, state.audio.context.currentTime + 1.2);
        icon.className = 'fa-solid fa-volume-xmark';
        label.innerText = 'Soundscape: Off';
        state.audio.isPlaying = false;
        
        // Stop alignment sound if active
        if (state.audio.humNode) {
            state.audio.humNode.gainNode.gain.setTargetAtTime(0, state.audio.context.currentTime, 0.1);
        }
    } else {
        // Fade in
        state.audio.gainNode.gain.linearRampToValueAtTime(0.2, state.audio.context.currentTime + 1.5);
        icon.className = 'fa-solid fa-volume-high';
        label.innerText = 'Soundscape: On';
        state.audio.isPlaying = true;
        
        // Connect alignment hum if we are in decoder section
        startDecoderHum();
        playSynthBeep(440, 'triangle', 0.15, 0.05);
    }
}

// Play modular synthesizer sounds for UI events
function playSynthBeep(freq, type, duration, volume) {
    if (!state.audio.context || !state.audio.isPlaying) return;
    
    const osc = state.audio.context.createOscillator();
    const gain = state.audio.context.createGain();
    
    osc.type = type || 'sine';
    osc.frequency.setValueAtTime(freq, state.audio.context.currentTime);
    
    gain.gain.setValueAtTime(volume || 0.1, state.audio.context.currentTime);
    // Exponential decay
    gain.gain.exponentialRampToValueAtTime(0.0001, state.audio.context.currentTime + duration);
    
    osc.connect(gain);
    gain.connect(state.audio.context.destination);
    
    osc.start();
    osc.stop(state.audio.context.currentTime + duration);
}

/* ==========================================================================
   OBSERVATORY / SIMULATOR SYSTEM
   ========================================================================== */

function initObservatory() {
    state.simulator.canvas = document.getElementById('simulator-canvas');
    state.simulator.ctx = state.simulator.canvas.getContext('2d');
    
    // Fit canvas dynamically
    resizeSimulator();
    window.addEventListener('resize', resizeSimulator);
    
    // Load initial phenomenon (Black hole)
    selectObservation(0);
}

function resizeSimulator() {
    if (!state.simulator.canvas) return;
    const box = state.simulator.canvas.parentElement;
    state.simulator.canvas.width = box.clientWidth;
    state.simulator.canvas.height = box.clientHeight || 350;
}

function selectObservation(index) {
    // Stop active simulation loops
    if (state.simulator.animationId) {
        cancelAnimationFrame(state.simulator.animationId);
    }
    
    state.activeEnigma = index;
    const data = ENIGMAS_DATA[index];
    
    // 1. Update text displays
    document.getElementById('visualizer-title').innerText = `${data.title} Simulator`;
    document.getElementById('coords-text').innerText = data.coords;
    
    // Type out details in logs
    const logBox = document.getElementById('log-text');
    logBox.innerHTML = '';
    
    // Log entry animation
    let delay = 0;
    data.logs.forEach((line, lineIdx) => {
        setTimeout(() => {
            const p = document.createElement('p');
            p.innerHTML = `<span class="log-date">[SEC ${120 + lineIdx * 15}s]</span> ${line}`;
            logBox.appendChild(p);
            logBox.scrollTop = logBox.scrollHeight;
            playSynthBeep(600 + lineIdx * 100, 'sine', 0.05, 0.01);
        }, delay);
        delay += 600;
    });

    // Write primary details
    const logDesc = document.createElement('p');
    logDesc.style.marginTop = '1rem';
    logDesc.style.color = '#94a3b8';
    logDesc.style.borderTop = '1px solid rgba(255, 255, 255, 0.05)';
    logDesc.style.paddingTop = '0.5rem';
    logDesc.innerText = data.description;
    setTimeout(() => { logBox.appendChild(logDesc); }, delay);

    // 2. Generate dynamic inputs
    const controlsBox = document.getElementById('controls-inputs');
    controlsBox.innerHTML = '';
    
    state.simulator.params = {}; // reset params

    data.controls.forEach(ctrl => {
        state.simulator.params[ctrl.type] = ctrl.value;
        
        const group = document.createElement('div');
        group.className = 'slider-group';
        
        let sliderColorClass = '';
        if (index === 1) sliderColorClass = 'slider-purple';
        else if (index === 2) sliderColorClass = 'slider-magenta';
        
        group.innerHTML = `
            <div class="slider-label-row">
                <span>${ctrl.label}</span>
                <span class="accent-val" id="val-${ctrl.id}">${ctrl.value} ${ctrl.unit}</span>
            </div>
            <input type="range" id="${ctrl.id}" min="${ctrl.min}" max="${ctrl.max}" value="${ctrl.value}" class="neon-slider ${sliderColorClass}">
        `;
        controlsBox.appendChild(group);
        
        // Listen to updates
        const input = group.querySelector('input');
        input.addEventListener('input', (e) => {
            const val = parseFloat(e.target.value);
            state.simulator.params[ctrl.type] = val;
            document.getElementById(`val-${ctrl.id}`).innerText = `${val} ${ctrl.unit}`;
            
            // Audio sound effect feedback for parameter adjustments
            playSynthBeep(300 + val * 5, 'sine', 0.08, 0.02);
            
            // Update HUD values immediately
            updateHUD(index);
        });
    });

    // 3. Update active sidebar visual highlight
    const btns = document.querySelectorAll('.selector-btn');
    btns.forEach((btn, idx) => {
        if (idx === index) btn.classList.add('active');
        else btn.classList.remove('active');
    });
    
    // Play navigation chirp
    playSynthBeep(880, 'sine', 0.1, 0.04);
    
    // Setup and trigger HUD overlays
    updateHUD(index);
    
    // Update educational study contents
    updateStudentContent(index);
    
    // 4. Start new animation render loop
    state.simulator.time = 0;
    runSimulationLoop();
}

function updateHUD(index) {
    const hud = document.getElementById('hud-overlay');
    hud.innerHTML = '';
    
    if (index === 0) { // Black hole
        hud.innerHTML = `
            <div class="hud-item">GRAVITATIONAL WARPING: <span id="hud-lens">6.2 G-deg</span></div>
            <div class="hud-item">SINGULARITY FLUX: <span id="hud-flux">84%</span></div>
            <div class="hud-item">COORDINATE TIME CORR: <span id="hud-time">1:4.82</span></div>
        `;
    } else if (index === 1) { // Dark Matter
        hud.innerHTML = `
            <div class="hud-item">FILAMENT BRIGHTNESS: <span id="hud-web">48.2%</span></div>
            <div class="hud-item">BARYON ATTRACTION: <span id="hud-att">Active</span></div>
        `;
    } else if (index === 2) { // FRB
        hud.innerHTML = `
            <div class="hud-item">BURST ENERGY OUTPUT: <span id="hud-frb">10^35 Joules</span></div>
            <div class="hud-item">REDSHIFT (z): <span id="hud-z">0.452</span></div>
        `;
    } else if (index === 3) { // Rogue planet
        hud.innerHTML = `
            <div class="hud-item">SURFACE TEMP: <span id="hud-t">4.2 Kelvin</span></div>
            <div class="hud-item">SCAN GRID FIDELITY: <span id="hud-fid">98.4%</span></div>
        `;
    } else { // Great attractor
        hud.innerHTML = `
            <div class="hud-item">ACCELERATION: <span id="hud-acc">621 km/s²</span></div>
            <div class="hud-item">OBSCURITY PERCENTAGE: <span id="hud-obs">91.8%</span></div>
        `;
    }
}

// Master rendering loop for the Observation Lab Canvas
function runSimulationLoop() {
    const canvas = state.simulator.canvas;
    const ctx = state.simulator.ctx;
    
    if (!canvas || !ctx) return;
    
    state.simulator.time += 0.03;
    
    // Clear simulator canvas with dark backing
    ctx.fillStyle = '#020306';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    const cx = canvas.width / 2;
    const cy = canvas.height / 2;
    
    // Call specific visualizers depending on what index is active
    switch(state.activeEnigma) {
        case 0:
            renderBlackHoleSimulator(ctx, cx, cy, state.simulator.params);
            break;
        case 1:
            renderDarkMatterNetSimulator(ctx, cx, cy, state.simulator.params);
            break;
        case 2:
            renderFRBSimulator(ctx, cx, cy, state.simulator.params);
            break;
        case 3:
            renderRoguePlanetScanner(ctx, cx, cy, state.simulator.params);
            break;
        case 4:
            renderGreatAttractorSimulator(ctx, cx, cy, state.simulator.params);
            break;
    }
    
    // Draw sci-fi oscilloscope boundaries on HUD
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.03)';
    ctx.lineWidth = 1;
    ctx.strokeRect(10, 10, canvas.width - 20, canvas.height - 20);
    
    // Live update state inspector if open and active
    if (state.drawer && state.drawer.isOpen && state.drawer.activeTab === 2) {
        updateLiveInspector();
    }
    
    state.simulator.animationId = requestAnimationFrame(runSimulationLoop);
}

/* --- Simulator 1: Black Hole Gravitational Lensing accretion --- */
function renderBlackHoleSimulator(ctx, cx, cy, params) {
    const r_s = params.mass || 40;
    const spin = (params.spin || 5) * 0.1;
    const lensing = params.lensing || 6;
    const time = state.simulator.time;
    
    // 1. Accretion disk background dust and heat waves
    const particleCount = 120;
    for (let i = 0; i < particleCount; i++) {
        const factor = (i / particleCount);
        const radius = r_s * 1.5 + factor * 140;
        const angle = i * 2.4 + time * (spin * (35 / radius));
        
        // Gravitational lensing warps dust into an offset oval and secondary ring
        const lensOffsetY = Math.sin(angle) * (radius * 0.2) * (lensing * 0.2);
        const x = cx + Math.cos(angle) * radius;
        const y = cy + Math.sin(angle) * (radius * 0.25) - Math.abs(Math.cos(angle)) * (radius * 0.15) * (lensing * 0.4);
        
        const size = Math.max(1, (1 - factor) * 4);
        ctx.fillStyle = i % 2 === 0 ? `rgba(245, 158, 11, ${0.4 + (1-factor)*0.6})` : `rgba(236, 72, 153, ${0.3 + (1-factor)*0.5})`;
        ctx.beginPath();
        ctx.arc(x, y, size, 0, Math.PI * 2);
        ctx.fill();
    }
    
    // 2. Glowing photon sphere background
    const grad = ctx.createRadialGradient(cx, cy, r_s, cx, cy, r_s * 1.35 + (lensing * 6));
    grad.addColorStop(0, '#ffffff');
    grad.addColorStop(0.1, 'rgba(253, 224, 71, 0.9)'); // bright yellow
    grad.addColorStop(0.5, 'rgba(219, 39, 119, 0.6)'); // glowing magenta
    grad.addColorStop(1, 'transparent');
    ctx.fillStyle = grad;
    ctx.beginPath();
    ctx.arc(cx, cy, r_s * 1.35 + (lensing * 6), 0, Math.PI * 2);
    ctx.fill();
    
    // 3. Solid Event Horizon (Black core)
    ctx.fillStyle = '#000000';
    ctx.beginPath();
    ctx.arc(cx, cy, r_s, 0, Math.PI * 2);
    ctx.fill();
    
    // Update active HUD values
    const lensingDisplay = document.getElementById('hud-lens');
    const fluxDisplay = document.getElementById('hud-flux');
    if (lensingDisplay) lensingDisplay.innerText = `${(lensing * 1.4).toFixed(2)} G-deg`;
    if (fluxDisplay) fluxDisplay.innerText = `${Math.floor(70 + spin * 10 + r_s * 0.2)}%`;
}

/* --- Simulator 2: Dark Matter Network Filaments --- */
let dmParticles = [];
function renderDarkMatterNetSimulator(ctx, cx, cy, params) {
    const density = params.density || 20;
    const expansion = (params.expansion || 3) * 0.2;
    const nodesCount = params.nodes || 40;
    const time = state.simulator.time;
    
    // Regenerate nodes array if count changes
    if (dmParticles.length !== nodesCount) {
        dmParticles = [];
        for (let i = 0; i < nodesCount; i++) {
            dmParticles.push({
                x: Math.random() * ctx.canvas.width,
                y: Math.random() * ctx.canvas.height,
                vx: (Math.random() - 0.5) * 1.5,
                vy: (Math.random() - 0.5) * 1.5,
                pulseOffset: Math.random() * Math.PI
            });
        }
    }
    
    // Draw cosmic filaments (lines between nodes)
    ctx.strokeStyle = `rgba(139, 92, 246, ${0.15 + (density * 0.005)})`;
    ctx.lineWidth = 1;
    
    dmParticles.forEach((p, idx) => {
        // Move particles reacting to expansion rate
        p.x += p.vx * (1 + expansion);
        p.y += p.vy * (1 + expansion);
        
        // Bounce from canvas edges
        if (p.x < 15 || p.x > ctx.canvas.width - 15) p.vx *= -1;
        if (p.y < 15 || p.y > ctx.canvas.height - 15) p.vy *= -1;
        
        // Draw filaments connection lines to nearby nodes
        for (let j = idx + 1; j < dmParticles.length; j++) {
            const dest = dmParticles[j];
            const dist = Math.hypot(dest.x - p.x, dest.y - p.y);
            if (dist < 130) {
                ctx.beginPath();
                ctx.moveTo(p.x, p.y);
                ctx.lineTo(dest.x, dest.y);
                ctx.stroke();
            }
        }
        
        // Render node points (glowing galaxy clusters)
        const pulse = 0.5 + Math.sin(time * 2 + p.pulseOffset) * 0.5;
        const radius = 2 + pulse * 4 * (density * 0.04);
        
        const grad = ctx.createRadialGradient(p.x, p.y, 0, p.x, p.y, radius * 3);
        grad.addColorStop(0, 'rgba(0, 242, 254, 0.9)');
        grad.addColorStop(0.3, 'rgba(168, 85, 247, 0.5)');
        grad.addColorStop(1, 'transparent');
        
        ctx.fillStyle = grad;
        ctx.beginPath();
        ctx.arc(p.x, p.y, radius * 3, 0, Math.PI * 2);
        ctx.fill();
        
        ctx.fillStyle = '#ffffff';
        ctx.beginPath();
        ctx.arc(p.x, p.y, 1.5, 0, Math.PI * 2);
        ctx.fill();
    });
    
    // Update active HUD
    const webDisplay = document.getElementById('hud-web');
    if (webDisplay) webDisplay.innerText = `${(density * 1.8 + expansion * 2).toFixed(1)}%`;
}

/* --- Simulator 3: Fast Radio Burst Radiation Waveform --- */
function renderFRBSimulator(ctx, cx, cy, params) {
    const freq = params.freq || 40;
    const dispersion = params.dispersion || 700;
    const pulseWidth = params.pulse || 8;
    const time = state.simulator.time;
    
    // Draw background pulsating magnetar star
    const starRad = 30 + Math.sin(time * 5) * 4;
    const starGrad = ctx.createRadialGradient(cx, cy, 5, cx, cy, starRad * 2);
    starGrad.addColorStop(0, '#ffffff');
    starGrad.addColorStop(0.2, 'rgba(219, 39, 119, 0.8)');
    starGrad.addColorStop(0.6, 'rgba(147, 51, 234, 0.3)');
    starGrad.addColorStop(1, 'transparent');
    ctx.fillStyle = starGrad;
    ctx.beginPath();
    ctx.arc(cx, cy, starRad * 2, 0, Math.PI * 2);
    ctx.fill();
    
    // Core Magnetar
    ctx.fillStyle = '#ffffff';
    ctx.beginPath();
    ctx.arc(cx, cy, starRad, 0, Math.PI * 2);
    ctx.fill();
    
    // Magnetic force field loops
    ctx.strokeStyle = 'rgba(0, 242, 254, 0.2)';
    ctx.lineWidth = 1;
    for (let i = 0; i < 4; i++) {
        const loopH = 40 + i * 20;
        ctx.beginPath();
        ctx.ellipse(cx, cy, starRad + i * 15, loopH, time * 0.2, 0, Math.PI * 2);
        ctx.stroke();
    }
    
    // Pulsating burst beams (simulating intergalactic propagation)
    const waveCount = 5;
    ctx.strokeStyle = 'rgba(219, 39, 119, 0.8)';
    ctx.lineWidth = 2.5;
    
    const beamAngle = time * 0.1;
    
    for (let side = -1; side <= 1; side += 2) {
        for (let i = 0; i < waveCount; i++) {
            // Pulse propagates outward
            const progress = ((time * 30 + i * 20) % 150) + starRad;
            const size = progress * 0.35;
            
            // Sweep frequency effects
            ctx.beginPath();
            ctx.ellipse(
                cx + Math.cos(beamAngle + (side === 1 ? 0 : Math.PI)) * progress,
                cy + Math.sin(beamAngle + (side === 1 ? 0 : Math.PI)) * progress,
                pulseWidth * 1.5,
                size,
                beamAngle + Math.PI/2,
                -Math.PI / 3,
                Math.PI / 3
            );
            
            // Neon Cyan / Neon Magenta wave variation
            ctx.strokeStyle = i % 2 === 0 ? '#ec4899' : '#06b6d4';
            ctx.shadowColor = ctx.strokeStyle;
            ctx.shadowBlur = 8;
            ctx.stroke();
        }
    }
    ctx.shadowBlur = 0; // reset
    
    // Update active HUD
    const zDisplay = document.getElementById('hud-z');
    if (zDisplay) zDisplay.innerText = `${(dispersion / 1500).toFixed(3)}`;
}

/* --- Simulator 4: Rogue Planet thermal grid scanner --- */
function renderRoguePlanetScanner(ctx, cx, cy, params) {
    const scanFreq = params.scanner || 15;
    const geoHeat = params.temp || 3;
    const filter = params.filter || 2;
    const time = state.simulator.time;
    
    const radius = 80;
    
    // 1. Draw pitch-black planet sphere body
    ctx.fillStyle = '#060812';
    ctx.beginPath();
    ctx.arc(cx, cy, radius, 0, Math.PI * 2);
    ctx.fill();
    
    // Outer atmospheric halo
    const atmosGrad = ctx.createRadialGradient(cx, cy, radius, cx, cy, radius + 25);
    atmosGrad.addColorStop(0, 'rgba(59, 130, 246, 0.45)');
    if (filter === 1) atmosGrad.addColorStop(0.5, 'rgba(139, 92, 246, 0.25)');
    else atmosGrad.addColorStop(0.5, 'rgba(0, 242, 254, 0.2)');
    atmosGrad.addColorStop(1, 'transparent');
    ctx.fillStyle = atmosGrad;
    ctx.beginPath();
    ctx.arc(cx, cy, radius + 25, 0, Math.PI * 2);
    ctx.fill();
    
    // 2. Draw active thermal cracks (volcanic hydrothermal vents under thick ice sheets)
    ctx.strokeStyle = `rgba(168, 85, 247, ${0.4 + (geoHeat * 0.05)})`;
    ctx.shadowColor = '#a855f7';
    ctx.shadowBlur = 10;
    ctx.lineWidth = 2;
    
    ctx.beginPath();
    // Crack 1
    ctx.moveTo(cx - 50, cy - 20);
    ctx.lineTo(cx - 20, cy - 10);
    ctx.lineTo(cx + 10, cy - 30);
    ctx.lineTo(cx + 40, cy - 25);
    // Crack 2
    ctx.moveTo(cx - 30, cy + 30);
    ctx.lineTo(cx, cy + 15);
    ctx.lineTo(cx + 35, cy + 35);
    ctx.stroke();
    
    ctx.shadowBlur = 0; // reset
    
    // 3. Matrix scanning overlay beam line sweeping down the planet
    const scanY = cy - radius - 10 + ((time * (scanFreq * 0.7)) % (radius * 2 + 20));
    
    // Glowing laser scan line
    ctx.strokeStyle = 'rgba(0, 242, 254, 0.8)';
    ctx.lineWidth = 1.5;
    ctx.shadowColor = '#06b6d4';
    ctx.shadowBlur = 12;
    
    ctx.beginPath();
    ctx.moveTo(cx - radius - 15, scanY);
    ctx.lineTo(cx + radius + 15, scanY);
    ctx.stroke();
    
    ctx.shadowBlur = 0; // reset
    
    // Digital scanning lines grid covering the scanned zone
    ctx.fillStyle = 'rgba(6, 182, 212, 0.06)';
    ctx.fillRect(cx - radius, cy - radius, radius * 2, scanY - (cy - radius));
    
    // Scanning diagnostic target boxes
    ctx.strokeStyle = 'rgba(0, 242, 254, 0.35)';
    ctx.strokeRect(cx - radius - 5, cy - radius - 5, radius * 2 + 10, radius * 2 + 10);
    
    ctx.beginPath();
    ctx.arc(cx, cy, radius, 0, Math.PI * 2);
    ctx.stroke();
    
    // Update active HUD
    const surfaceT = document.getElementById('hud-t');
    const fidelityDisplay = document.getElementById('hud-fid');
    if (surfaceT) surfaceT.innerText = `${(3.1 + geoHeat * 0.3).toFixed(1)} Kelvin`;
    if (fidelityDisplay) fidelityDisplay.innerText = `${Math.floor(95 + (scanFreq * 0.1))}%`;
}

/* --- Simulator 5: The Great Attractor gravity well --- */
let attractorStars = [];
function renderGreatAttractorSimulator(ctx, cx, cy, params) {
    const pull = params.pull || 50;
    const clusterCount = params.count || 30;
    const dust = params.dust || 45;
    const time = state.simulator.time;
    
    // Populate gravity stars/galaxy clusters
    if (attractorStars.length < clusterCount) {
        while (attractorStars.length < clusterCount) {
            const angle = Math.random() * Math.PI * 2;
            const distance = Math.random() * 200 + 40;
            attractorStars.push({
                angle: angle,
                distance: distance,
                speed: (Math.random() * 0.02 + 0.005),
                size: Math.random() * 2 + 1,
                color: Math.random() > 0.5 ? '#60a5fa' : '#f87171' // Red vs Blue galaxy shifts
            });
        }
    }
    // Trim extra particles
    if (attractorStars.length > clusterCount) {
        attractorStars = attractorStars.slice(0, clusterCount);
    }
    
    // Draw cosmic swirling center (gravity anomaly core)
    const coreRad = 15 + Math.sin(time * 3) * 3;
    const centerGrad = ctx.createRadialGradient(cx, cy, 0, cx, cy, 80);
    centerGrad.addColorStop(0, 'rgba(0, 0, 0, 0.95)');
    centerGrad.addColorStop(0.2, 'rgba(239, 68, 68, 0.45)'); // Glowing dark red pull
    centerGrad.addColorStop(0.7, 'rgba(139, 92, 246, 0.1)');
    centerGrad.addColorStop(1, 'transparent');
    
    ctx.fillStyle = centerGrad;
    ctx.beginPath();
    ctx.arc(cx, cy, 85, 0, Math.PI * 2);
    ctx.fill();
    
    // Core singularity dot
    ctx.fillStyle = '#000000';
    ctx.beginPath();
    ctx.arc(cx, cy, coreRad, 0, Math.PI * 2);
    ctx.fill();
    
    // Swirling gravity grid spirals
    ctx.strokeStyle = 'rgba(239, 68, 68, 0.08)';
    ctx.lineWidth = 1;
    for (let r = 20; r < 240; r += 30) {
        ctx.beginPath();
        ctx.arc(cx, cy, r, 0, Math.PI * 2);
        ctx.stroke();
    }
    
    // Render spirals and galactic coordinates
    attractorStars.forEach((star) => {
        // Galaxies spin and spiral inward under gravitational pull
        star.angle += star.speed * (pull * 0.03);
        star.distance -= (pull * 0.015);
        
        // Reset when galaxy falls into Attractor core
        if (star.distance < coreRad) {
            star.distance = Math.random() * 150 + 100;
            star.angle = Math.random() * Math.PI * 2;
        }
        
        // Stretched elliptical orbit projections
        const posX = cx + Math.cos(star.angle) * star.distance;
        const posY = cy + Math.sin(star.angle) * (star.distance * 0.6);
        
        // Doppler blue/red shift representation
        ctx.fillStyle = star.color;
        ctx.shadowColor = star.color;
        ctx.shadowBlur = 3;
        ctx.beginPath();
        ctx.arc(posX, posY, star.size, 0, Math.PI * 2);
        ctx.fill();
    });
    ctx.shadowBlur = 0; // reset
    
    // Render space dust clouds (obscurant factor)
    ctx.fillStyle = `rgba(15, 23, 42, ${dust * 0.007})`;
    ctx.fillRect(10, 10, ctx.canvas.width - 20, ctx.canvas.height - 20);
    
    // Update active HUD
    const accDisplay = document.getElementById('hud-acc');
    const obsDisplay = document.getElementById('hud-obs');
    if (accDisplay) accDisplay.innerText = `${(510 + pull * 2.2).toFixed(0)} km/s²`;
    if (obsDisplay) obsDisplay.innerText = `${dust.toFixed(1)}%`;
}

/* ==========================================================================
   INTERSTELLAR SIGNAL DECODER SYSTEM (MINI-GAME)
   ========================================================================== */

function initDecoder() {
    state.decoder.canvas = document.getElementById('decoder-canvas');
    state.decoder.ctx = state.decoder.canvas.getContext('2d');
    
    // Fit canvas dynamically
    resizeDecoderCanvas();
    window.addEventListener('resize', resizeDecoderCanvas);
    
    // Set interactive listeners on the telescope dials
    setupDecoderControls();
    
    // Start continuous decoder oscilloscope drawing loop
    runDecoderOscilloscopeLoop();
}

function resizeDecoderCanvas() {
    if (!state.decoder.canvas) return;
    const box = state.decoder.canvas.parentElement;
    state.decoder.canvas.width = box.clientWidth;
    state.decoder.canvas.height = box.clientHeight || 300;
}

function setupDecoderControls() {
    const dials = [
        { id: "dial-frequency", key: "freq", unit: ".0 GHz" },
        { id: "dial-filter", key: "filter", unit: ".0 Hz" },
        { id: "dial-phase", key: "phase", unit: "°" },
        { id: "dial-gain", key: "gain", unit: ".0 dB" }
    ];
    
    dials.forEach(dial => {
        const input = document.getElementById(dial.id);
        const valSpan = document.getElementById(`val-${dial.id.replace('dial-', '')}`);
        
        // Initialize current state values from elements
        state.decoder.current[dial.key] = parseFloat(input.value);
        
        input.addEventListener('input', (e) => {
            const val = parseFloat(e.target.value);
            state.decoder.current[dial.key] = val;
            valSpan.innerText = `${val}${dial.unit}`;
            
            // Dynamic Web Audio API feedback depending on signal resonance matching!
            playTelescopeStaticHum();
            
            // Check resonance alignment
            checkSignalAlignment();
        });
    });
    
    // Decode Action button trigger
    const decodeBtn = document.getElementById('decode-btn');
    decodeBtn.addEventListener('click', executeTerminalDecoding);
}

// Generates dynamic interactive statics synth humming depending on dial status
function playTelescopeStaticHum() {
    if (!state.audio.context || !state.audio.isPlaying) return;
    
    // Initialize continuous hum oscillator
    if (!state.audio.humNode) {
        const osc = state.audio.context.createOscillator();
        const gainNode = state.audio.context.createGain();
        const bpf = state.audio.context.createBiquadFilter();
        
        osc.type = 'triangle';
        osc.frequency.setValueAtTime(120, state.audio.context.currentTime); // Deep pitch hum
        
        bpf.type = 'bandpass';
        bpf.Q.setValueAtTime(5, state.audio.context.currentTime);
        bpf.frequency.setValueAtTime(300, state.audio.context.currentTime);
        
        gainNode.gain.setValueAtTime(0.015, state.audio.context.currentTime);
        
        osc.connect(bpf);
        bpf.connect(gainNode);
        gainNode.connect(state.audio.context.destination);
        osc.start();
        
        state.audio.humNode = { osc, gainNode, bpf };
    }
    
    // Update hum pitch & volume based on dial frequencies and alignment success
    const alignment = computeAlignmentRatio();
    const frequencyFactor = state.decoder.current.freq;
    
    // As player matches signal, hum becomes clean and high-pitched harmonic chord
    const baseFreq = 80 + frequencyFactor * 1.5;
    const filterFreq = 200 + alignment * 800;
    
    state.audio.humNode.osc.frequency.setTargetAtTime(baseFreq, state.audio.context.currentTime, 0.05);
    state.audio.humNode.bpf.frequency.setTargetAtTime(filterFreq, state.audio.context.currentTime, 0.05);
    state.audio.humNode.gainNode.gain.setTargetAtTime(0.01 + (alignment * 0.02), state.audio.context.currentTime, 0.05);
}

function startDecoderHum() {
    if (state.audio.isPlaying) {
        playTelescopeStaticHum();
    }
}

// Compute mathematically how close current dials match the astronomical target signal
function computeAlignmentRatio() {
    const cur = state.decoder.current;
    const tar = state.decoder.target;
    
    // Standard differences normalized
    const diffFreq = Math.abs(cur.freq - tar.freq) / 90;
    const diffFilter = Math.abs(cur.filter - tar.filter) / 45;
    const diffPhase = Math.abs(cur.phase - tar.phase) / 360;
    const diffGain = Math.abs(cur.gain - tar.gain) / 90;
    
    const avgDiff = (diffFreq + diffFilter + diffPhase + diffGain) / 4;
    return Math.max(0, 1 - avgDiff); // 0.0 to 1.0
}

function checkSignalAlignment() {
    const alignment = computeAlignmentRatio();
    const percent = Math.floor(alignment * 100);
    
    const alignSpan = document.getElementById('match-percentage');
    alignSpan.innerText = `Alignment: ${percent}%`;
    
    const decodeBtn = document.getElementById('decode-btn');
    
    if (percent >= 94) {
        state.decoder.isAligned = true;
        alignSpan.classList.add('text-green');
        alignSpan.classList.remove('text-cyan');
        decodeBtn.disabled = false;
        
        // Pulse glow decoder button
        decodeBtn.classList.add('glow-active');
    } else {
        state.decoder.isAligned = false;
        alignSpan.classList.remove('text-green');
        alignSpan.classList.add('text-cyan');
        decodeBtn.disabled = true;
        decodeBtn.classList.remove('glow-active');
    }
}

// Waveforms visual renderer
function runDecoderOscilloscopeLoop() {
    const canvas = state.decoder.canvas;
    const ctx = state.decoder.ctx;
    
    if (!canvas || !ctx) return;
    
    // Clear canvas
    ctx.fillStyle = '#03060f';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    const time = Date.now() * 0.003;
    const centerY = canvas.height / 2;
    
    // 1. Draw Target astronomical signal (Cyan line)
    ctx.strokeStyle = 'rgba(6, 182, 212, 0.75)';
    ctx.lineWidth = 2;
    ctx.beginPath();
    
    const tFreq = state.decoder.target.freq * 0.0015;
    const tAmp = state.decoder.target.gain * 0.8;
    const tFilter = state.decoder.target.filter;
    const tPhase = (state.decoder.target.phase * Math.PI) / 180;
    
    for (let x = 0; x < canvas.width; x++) {
        // Composite mathematical target wave formula (complex harmonic wave)
        const y = centerY + Math.sin(x * tFreq + time * 1.5 + tPhase) * tAmp * Math.cos(x * 0.005);
        if (x === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
    }
    ctx.stroke();
    
    // 2. Draw Incoming scrambled signal (Magenta line)
    ctx.strokeStyle = 'rgba(236, 72, 153, 0.7)';
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    
    const cFreq = state.decoder.current.freq * 0.0015;
    const cAmp = state.decoder.current.gain * 0.8;
    const cFilter = state.decoder.current.filter;
    const cPhase = (state.decoder.current.phase * Math.PI) / 180;
    
    for (let x = 0; x < canvas.width; x++) {
        // Scrambled frequency depends on filter knob (adds noisy sine waves)
        const noise = Math.sin(x * 0.15 + time * 6) * cFilter * 0.6 * (1 - computeAlignmentRatio());
        const y = centerY + Math.sin(x * cFreq + time * 1.5 + cPhase) * cAmp * Math.cos(x * 0.005) + noise;
        
        if (x === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
    }
    ctx.stroke();
    
    state.decoder.animationId = requestAnimationFrame(runDecoderOscilloscopeLoop);
}

// Typwriter terminal printout when signal decoded is complete
function executeTerminalDecoding() {
    if (!state.decoder.isAligned) return;
    
    const term = document.getElementById('terminal-body');
    const decodeBtn = document.getElementById('decode-btn');
    
    // Disable inputs & dials temporarily during scan
    decodeBtn.disabled = true;
    playSynthBeep(880, 'sine', 0.4, 0.1);
    setTimeout(() => { playSynthBeep(1200, 'sine', 0.6, 0.1); }, 150);
    
    // Append terminal messages with sci-fi typewriter delays
    term.innerHTML = `<p class="terminal-line text-green">> DECODER ARRAY ENGAGED. Synchronizing harmonic phase locks...</p>`;
    
    const logs = [
        { text: "> Lock established at 8.41 GHz array coordinate. Attenuating galactic static...", type: "cyan", delay: 800 },
        { text: "> Phase deviation variance adjusted to 0.0003 radians.", type: "cyan", delay: 1600 },
        { text: "> Signal spectrum analysis confirms deep-space source of organic telemetry.", type: "green", delay: 2400 },
        { text: "> DECODING COMPLETE. RECONSTRUCTING TELEMETRIC MESSAGE DATA PACKET...", type: "magenta", delay: 3200 },
        { text: "==========================================================", type: "normal", delay: 4000 },
        { text: "TRANSMISSION SOURCE: Sagittarius A* Gravitational Margin (Event Horizon Boundary)", type: "green", delay: 4600 },
        { text: "MESSAGE LOG DETECTED: 'In the center of the dark, light is not deleted, only folded into tomorrow.'", type: "magenta", delay: 5600 },
        { text: "==========================================================", type: "normal", delay: 6600 },
        { text: "> TELEMETRY LOGGED. Observatory archive updated. Node online.", type: "cyan", delay: 7200 }
    ];
    
    logs.forEach(log => {
        setTimeout(() => {
            const p = document.createElement('p');
            p.className = `terminal-line ${log.type === 'cyan' ? 'text-cyan' : (log.type === 'green' ? 'text-green' : (log.type === 'magenta' ? 'text-magenta' : ''))}`;
            p.innerText = log.text;
            term.appendChild(p);
            term.scrollTop = term.scrollHeight;
            
            // Click/Chirp sound feedback for logging text lines
            playSynthBeep(700 + Math.random() * 200, 'sine', 0.04, 0.015);
        }, log.delay);
    });
}

/* ==========================================================================
   EVENT LISTENERS & UTILITIES
   ========================================================================== */

function setupEventListeners() {
    // 1. Audio toggle button action
    const audioBtn = document.getElementById('audio-toggle');
    if (audioBtn) audioBtn.addEventListener('click', toggleSoundscape);
    
    // 2. Smooth navbar linkage active scrolling highlights
    const sections = document.querySelectorAll('section');
    const navLinks = document.querySelectorAll('.nav-links a');
    
    window.addEventListener('scroll', () => {
        let current = '';
        const scrollPos = window.scrollY + 100;
        
        sections.forEach(sec => {
            const top = sec.offsetTop;
            const height = sec.offsetHeight;
            if (scrollPos >= top && scrollPos < top + height) {
                current = sec.getAttribute('id');
            }
        });
        
        navLinks.forEach(link => {
            link.classList.remove('active');
            if (link.getAttribute('href').slice(1) === current) {
                link.classList.add('active');
            }
        });
    });
    
    // Card clicks smooth scrolling to Observatory Lab
    const cards = document.querySelectorAll('.phenomenon-card');
    cards.forEach(card => {
        card.addEventListener('click', () => {
            document.getElementById('observatory').scrollIntoView({ behavior: 'smooth' });
        });
    });
    
    // 3. Sectors dropdown toggle for touch and click devices
    const sectorsContainer = document.querySelector('.sectors-dropdown-container');
    const sectorsToggle = document.querySelector('.sectors-dropdown-container .sectors-toggle');
    if (sectorsContainer && sectorsToggle) {
        sectorsToggle.addEventListener('click', (event) => {
            event.stopPropagation();
            const isOpen = sectorsContainer.classList.toggle('open');
            sectorsToggle.setAttribute('aria-expanded', String(isOpen));
        });

        document.addEventListener('click', (event) => {
            if (!sectorsContainer.contains(event.target)) {
                sectorsContainer.classList.remove('open');
                sectorsToggle.setAttribute('aria-expanded', 'false');
            }
        });
    }

    // 4. Student drawer bindings
    const studentBtn = document.getElementById('student-toggle');
    if (studentBtn) {
        studentBtn.setAttribute('aria-expanded', String(state.drawer.isOpen));
        studentBtn.addEventListener('click', toggleStudentDrawer);
    }
    const closeBtn = document.getElementById('drawer-close');
    if (closeBtn) {
        closeBtn.addEventListener('click', toggleStudentDrawer);
    }
}

/* ==========================================================================
   STUDENT STUDY LAB SYSTEM & HELPERS
   ========================================================================== */

function initStudentDrawer() {
    updateStudentContent(state.activeEnigma);
}

function toggleStudentDrawer() {
    const drawer = document.getElementById('student-drawer');
    if (!drawer) return;
    
    if (state.drawer.isOpen) {
        drawer.classList.remove('open');
        state.drawer.isOpen = false;
        playSynthBeep(400, 'sine', 0.12, 0.03);
    } else {
        drawer.classList.add('open');
        state.drawer.isOpen = true;
        updateStudentContent(state.activeEnigma);
        playSynthBeep(600, 'sine', 0.15, 0.03);
    }

    const studentBtn = document.getElementById('student-toggle');
    if (studentBtn) {
        studentBtn.setAttribute('aria-expanded', String(state.drawer.isOpen));
    }
}

function switchDrawerTab(tabIdx) {
    state.drawer.activeTab = tabIdx;
    
    const tabs = ['science', 'code', 'inspector'];
    tabs.forEach((tab, idx) => {
        const btn = document.getElementById(`tab-btn-${tab}`);
        const content = document.getElementById(`drawer-tab-${tab}`);
        
        if (idx === tabIdx) {
            if (btn) btn.classList.add('active');
            if (content) content.classList.add('active');
        } else {
            if (btn) btn.classList.remove('active');
            if (content) content.classList.remove('active');
        }
    });
    
    playSynthBeep(500 + tabIdx * 80, 'sine', 0.08, 0.02);
    
    if (tabIdx === 2) {
        updateLiveInspector();
    }
}

function updateStudentContent(index) {
    const scienceTab = document.getElementById('drawer-tab-science');
    const codeTab = document.getElementById('drawer-tab-code');
    
    if (scienceTab) {
        scienceTab.innerHTML = getStudyContent(index, 0);
    }
    if (codeTab) {
        codeTab.innerHTML = getStudyContent(index, 1);
    }
    
    updateLiveInspector();
}

function updateLiveInspector() {
    const inspector = document.getElementById('inspect-state');
    if (!inspector) return;
    
    // Create a student-friendly clone of state to inspect
    const stateClone = {
        activeEnigma: state.activeEnigma,
        activePhenomenon: ENIGMAS_DATA[state.activeEnigma].title,
        simulationTime: parseFloat(state.simulator.time.toFixed(2)),
        sliderParams: state.simulator.params,
        radioTuning: {
            target: state.decoder.target,
            player: state.decoder.current,
            resonanceMatch: `${Math.floor(computeAlignmentRatio() * 100)}%`,
            isAligned: state.decoder.isAligned
        },
        audioEngine: {
            isPlaying: state.audio.isPlaying,
            sampleRate: state.audio.context ? `${state.audio.context.sampleRate} Hz` : "Inactive"
        }
    };
    
    inspector.innerText = JSON.stringify(stateClone, null, 2);
}

function getStudyContent(index, tab) {
    if (tab === 0) { // Science & Math
        if (index === 0) {
            return `
                <h3>🔬 Black Hole Singularity</h3>
                <p>In general relativity, a <strong>Black Hole</strong> is a region of spacetime where gravitational acceleration is so intense that nothing—not even light—can escape its boundary.</p>
                <div class="equation-box">
                    <span class="equation-label">Schwarzschild Radius Equation</span>
                    <span class="equation-math">R_s = \\frac{2GM}{c^2}</span>
                </div>
                <p><strong>R_s</strong> is the radius of the event horizon, <strong>G</strong> is the gravitational constant, <strong>M</strong> is the mass, and <strong>c</strong> is the speed of light. Inside this radius, gravity collapses matter into a single point of infinite density—the singularity.</p>
                <h4>Relativistic Gravitational Lensing</h4>
                <p>Because gravity bends space, light passing near the event horizon is deflected. This bends accretion dust into glowing streaks, creating the iconic halo silhouette.</p>
            `;
        } else if (index === 1) {
            return `
                <h3>🔬 Dark Matter Cosmic Scaffold</h3>
                <p><strong>Dark Matter</strong> is a hypothetical form of matter that does not interact with light or electromagnetic fields, making it completely invisible.</p>
                <div class="equation-box">
                    <span class="equation-label">Cosmic Density Parameter</span>
                    <span class="equation-math">Ω_{total} = Ω_b + Ω_{dm} + Ω_{de}</span>
                </div>
                <p>The total density of the universe consists of Baryonic (normal) matter <strong>Ω_b</strong> (approx 5%), Dark Matter <strong>Ω_dm</strong> (approx 27%), and Dark Energy <strong>Ω_de</strong> (approx 68%). Dark matter acts as an invisible gravity anchor seeding galaxy clusters.</p>
                <h4>Filaments & Cosmic Scaffolds</h4>
                <p>Galaxies sit along a vast cosmic web of invisible dark matter filaments. The gravitational attraction of these clusters is mapped by measuring how their mass distorts light from background galaxies.</p>
            `;
        } else if (index === 2) {
            return `
                <h3>🔬 Fast Radio Bursts (FRB)</h3>
                <p><strong>Fast Radio Bursts</strong> are millisecond-long, highly energetic pulses of radio emission originating from distant galaxies, packing the power of hundreds of millions of suns.</p>
                <div class="equation-box">
                    <span class="equation-label">Dispersion Measure Equation</span>
                    <span class="equation-math">DM = \\int_0^d n_e(s) ds</span>
                </div>
                <p>The <strong>Dispersion Measure (DM)</strong> integrates the free electron density <strong>n_e</strong> along the travel path. Because lower frequency radio waves travel slower through plasma, the burst arrives swept across time, revealing its travel distance!</p>
                <h4>The Magnetar Hypothesis</h4>
                <p>The leading explanation for FRBs points to magnetars—neutron stars with magnetic fields 1,000 times stronger than standard neutron stars. Crust ruptures trigger explosive coherent curvature radiation.</p>
            `;
        } else if (index === 3) {
            return `
                <h3>🔬 Nomadic Rogue Planets</h3>
                <p>A <strong>Rogue Planet</strong> is a massive planetary body that drifts freely in interstellar space, having been ejected gravitationally from its home stellar system during early solar formation.</p>
                <div class="equation-box">
                    <span class="equation-label">Geothermal Flux Balance</span>
                    <span class="equation-math">Q_{geo} - Q_{rad} = m \\cdot C_p \\cdot \\frac{dT}{dt}</span>
                </div>
                <p>Without a parent sun, the planet's surface is exposed to cosmic cold (approx 2.7K). However, radioactive decay in the core maintains geothermal flux, generating hydrothermal vents under thick surface ice sheets.</p>
                <h4>Atmospheric Scan Diagnostics</h4>
                <p>Active thermal scanning maps surface cracks. Crystallization of water and methane ice creates highly reflective sheets that insulate liquid under-ice oceans.</p>
            `;
        } else {
            return `
                <h3>🔬 The Great Attractor Anomaly</h3>
                <p>The <strong>Great Attractor</strong> is a massive gravitational anomaly located in the Zone of Avoidance (behind our galaxy's dusty plane) in the center of the Laniakea Supercluster.</p>
                <div class="equation-box">
                    <span class="equation-label">Keplerian Mass Deviation</span>
                    <span class="equation-math">v_{drift} = \\sqrt{\\frac{G \\cdot M_{attractor}}{r}}</span>
                </div>
                <p>Galaxies within hundreds of millions of light-years deviate from normal cosmic expansion, drifting at over 600 km/s toward Centaurus. This indicates a massive concentration equal to 10¹⁶ solar masses.</p>
                <h4>The Zone of Avoidance</h4>
                <p>Because the Attractor lies along the galactic disk, interstellar gas and dust block 90% of visible light, forcing astrophysicists to map it using deep infrared and radio wave telescope receivers.</p>
            `;
        }
    } else { // Canvas Code Breakdown (tab === 1)
        if (index === 0) {
            return `
                <h3>🎨 HTML5 Canvas Black Hole Mechanics</h3>
                <p>To simulate gravitational lensing and dust rotation on canvas, the code implements circular coordinate physics:</p>
                <div class="code-explain-box">
                    <code>const x = cx + Math.cos(angle) * radius;<br>
const y = cy + Math.sin(angle) * (radius * 0.25) - Math.abs(Math.cos(angle)) * (radius * 0.15) * (lensing * 0.4);</code>
                </div>
                <ul class="code-desc-list">
                    <li><strong>Accretion Disk Ellipse:</strong> Multiplying the Y coordinate by <code>0.25</code> squashes the circle into a flat orbital ellipse.</li>
                    <li><strong>Warping Factor:</strong> The subtraction of <code>Math.abs(Math.cos(angle)) * lensing</code> displaces particles behind the singularity vertically, rendering the iconic gravity-lens silhouette.</li>
                    <li><strong>Singularity Core:</strong> A black circular mask is rendered in the middle: <code>ctx.arc(cx, cy, r_s, 0, Math.PI * 2)</code>.</li>
                </ul>
            `;
        } else if (index === 1) {
            return `
                <h3>🎨 HTML5 Canvas Dark Matter Web</h3>
                <p>The cosmic network is drawn by linking moving galaxy nodes with dynamic gravitational filaments:</p>
                <div class="code-explain-box">
                    <code>const dist = Math.hypot(dest.x - p.x, dest.y - p.y);<br>
if (dist &lt; 130) {<br>
&nbsp;&nbsp;ctx.beginPath();<br>
&nbsp;&nbsp;ctx.moveTo(p.x, p.y);<br>
&nbsp;&nbsp;ctx.lineTo(dest.x, dest.y);<br>
&nbsp;&nbsp;ctx.stroke();<br>
}</code>
                </div>
                <ul class="code-desc-list">
                    <li><strong>Distance Formula:</strong> <code>Math.hypot</code> computes Euclidean distance using Pythagoras: <code>√(Δx² + Δy²)</code>.</li>
                    <li><strong>Soft Filaments:</strong> If nodes are within 130px, a connection line is stroked. The opacity scales with density: <code>rgba(139, 92, 246, density)</code>.</li>
                    <li><strong>Galaxy Clusters:</strong> Node coordinates drift according to expansion sliders. Radial gradients paint soft glowing galaxy bulbs.</li>
                </ul>
            `;
        } else if (index === 2) {
            return `
                <h3>🎨 HTML5 Canvas Radio Dispersion</h3>
                <p>To represent dispersed radio impulses propagating outward from a magnetar star, we use modulated canvas ellipses:</p>
                <div class="code-explain-box">
                    <code>const progress = ((time * 30 + i * 20) % 150) + starRad;<br>
ctx.ellipse(cx + Math.cos(beamAngle) * progress, cy + Math.sin(beamAngle) * progress, pulseWidth * 1.5, size, beamAngle + Math.PI/2, -Math.PI / 3, Math.PI / 3);</code>
                </div>
                <ul class="code-desc-list">
                    <li><strong>Outward Propagation:</strong> <code>progress</code> increases with elapsed time (using modulo to recycle waves).</li>
                    <li><strong>Elliptical Shockwaves:</strong> We use <code>ctx.ellipse</code> to draw curved arc wavefronts sweeping outward in opposite directions.</li>
                    <li><strong>Neon Wave Glow:</strong> Alternating waves stroke neon cyan and magenta colors utilizing <code>ctx.shadowBlur = 8</code> to simulate dispersed light spectra.</li>
                </ul>
            `;
        } else if (index === 3) {
            return `
                <h3>🎨 HTML5 Canvas Planetary Thermal Grid</h3>
                <p>To model a deep-space rogue world scanned by a scientific satellite array, we paint layers of heat scans:</p>
                <div class="code-explain-box">
                    <code>const scanY = cy - radius - 10 + ((time * (scanFreq * 0.7)) % (radius * 2 + 20));<br>
ctx.beginPath();<br>
ctx.moveTo(cx - radius - 15, scanY);<br>
ctx.lineTo(cx + radius + 15, scanY);<br>
ctx.stroke();</code>
                </div>
                <ul class="code-desc-list">
                    <li><strong>Linear Scan Sweep:</strong> <code>scanY</code> slides linearly down the planet bounds. The frequency is controlled directly by the interactive slider.</li>
                    <li><strong>Under-Ice Fissures:</strong> We draw active geothermal heat lines using purple lines and high shadow blurs (<code>ctx.shadowBlur = 10</code>) underneath the sweep line.</li>
                    <li><strong>Diagnostics:</strong> Outer diagnostic green/cyan boxes are painted using <code>ctx.strokeRect</code> to complete the sci-fi sensor theme.</li>
                </ul>
            `;
        } else {
            return `
                <h3>🎨 HTML5 Canvas Gravity Swarm</h3>
                <p>To render the massive gravity well pulling clusters toward its core, we execute a polar-to-Cartesian particle swirl:</p>
                <div class="code-explain-box">
                    <code>star.angle += star.speed * (pull * 0.03);<br>
star.distance -= (pull * 0.015);<br>
const posX = cx + Math.cos(star.angle) * star.distance;<br>
const posY = cy + Math.sin(star.angle) * (star.distance * 0.6);</code>
                </div>
                <ul class="code-desc-list">
                    <li><strong>Polar Spirals:</strong> Each galaxy particle tracks an <code>angle</code> and <code>distance</code>. Over time, distance decreases and angle increases, creating a beautiful spiral drift.</li>
                    <li><strong>Singularity Recycler:</strong> If a galaxy cluster hits the attractor center, its position resets to the outer boundary: <code>star.distance = Math.random() * 150 + 100</code>.</li>
                    <li><strong>Elliptical Flattening:</strong> Multiplying Y by <code>0.6</code> tilts the spiral plane, giving a 3D perspective to the massive attractor.</li>
                </ul>
            `;
        }
    }
}
